version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
